// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedTime  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoFile) Reset() {
	*x = ProtoFile{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFile) ProtoMessage() {}

func (x *ProtoFile) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFile.ProtoReflect.Descriptor instead.
func (*ProtoFile) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProtoFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProtoFile) GetModifiedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedTime
	}
	return nil
}

type ProtoTape struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Free          int64                  `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	Files         []*ProtoFile           `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoTape) Reset() {
	*x = ProtoTape{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoTape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoTape) ProtoMessage() {}

func (x *ProtoTape) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoTape.ProtoReflect.Descriptor instead.
func (*ProtoTape) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoTape) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *ProtoTape) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProtoTape) GetFree() int64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *ProtoTape) GetFiles() []*ProtoFile {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12 network.foxden.tapemgr.inventory\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n" +
	"\tProtoFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12?\n" +
	"\rmodified_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fmodifiedTime\"\x90\x01\n" +
	"\tProtoTape\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x03R\x04free\x12A\n" +
	"\x05files\x18\x04 \x03(\v2+.network.foxden.tapemgr.inventory.ProtoFileR\x05filesB1Z/github.com/FoxDenHome/tapemgr/storage/inventoryb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inventory_proto_goTypes = []any{
	(*ProtoFile)(nil),             // 0: network.foxden.tapemgr.inventory.ProtoFile
	(*ProtoTape)(nil),             // 1: network.foxden.tapemgr.inventory.ProtoTape
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_inventory_proto_depIdxs = []int32{
	2, // 0: network.foxden.tapemgr.inventory.ProtoFile.modified_time:type_name -> google.protobuf.Timestamp
	0, // 1: network.foxden.tapemgr.inventory.ProtoTape.files:type_name -> network.foxden.tapemgr.inventory.ProtoFile
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
